//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DzhafarliOrkhan320P.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class academics
    {
        public int id { get; set; }
        public string fio { get; set; }
        public Nullable<System.DateTime> bdate { get; set; }
        public string spec { get; set; }
        public Nullable<int> zyear { get; set; }
    }
}
