//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DzhafarliOrkhan320P.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class countries
    {
        public int id { get; set; }
        public string cname { get; set; }
        public string capital { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<int> population { get; set; }
        public string continent { get; set; }
    }
}
