//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DzhafarliOrkhan320P.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uchebka_orkhanEntities : DbContext
    {
        public uchebka_orkhanEntities()
            : base("name=uchebka_orkhanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<academics> academics { get; set; }
        public virtual DbSet<Animal_Dzhafarli> Animal_Dzhafarli { get; set; }
        public virtual DbSet<Control_Dzhafarli> Control_Dzhafarli { get; set; }
        public virtual DbSet<countries> countries { get; set; }
        public virtual DbSet<Countries_Dzhafarli> Countries_Dzhafarli { get; set; }
        public virtual DbSet<disciplines> disciplines { get; set; }
        public virtual DbSet<engineer> engineer { get; set; }
        public virtual DbSet<exams> exams { get; set; }
        public virtual DbSet<facults> facults { get; set; }
        public virtual DbSet<FlowersDzhafarli> FlowersDzhafarli { get; set; }
        public virtual DbSet<kafedra_mains> kafedra_mains { get; set; }
        public virtual DbSet<kafedras> kafedras { get; set; }
        public virtual DbSet<requests> requests { get; set; }
        public virtual DbSet<specs> specs { get; set; }
        public virtual DbSet<Student10> Student10 { get; set; }
        public virtual DbSet<students> students { get; set; }
        public virtual DbSet<students14> students14 { get; set; }
        public virtual DbSet<teachers> teachers { get; set; }
        public virtual DbSet<workers> workers { get; set; }
        public virtual DbSet<Licium> Licium { get; set; }
    }
}
