//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DzhafarliOrkhan320P.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class workers
    {
        public int id { get; set; }
        public string kafedra_code { get; set; }
        public string fio { get; set; }
        public string wpos { get; set; }
        public Nullable<int> salary { get; set; }
        public Nullable<int> chef { get; set; }
    
        public virtual kafedras kafedras { get; set; }
    }
}
